### ISSUE TITLE
Cannot GET /savegamepro

### ISSUE THREAD

**Issue by peterchen2001** [BayatGames/node-savegamepro-mysql#1]
After following the link to https://github.com/BayatGames/node-savegamepro-mysql#npm, I see the prompt "Example app listening on port 3000!", I think the server is running.

However, when i try to access http://localhost:3000/savegamepro via Firefox, It says below error:

Cannot GET /savegamepro

Anything am I missing?

**Comment by hasanbayatme** [comment]
Hello.
You don't need to access Save Game Pro page via there, it is only available for the API.
It is a POST-only page, not for GET and displaying anything, it accepts POST requests from Client.
If you have set it up, you can now call the API from Client-side.

Thanks!
