### ISSUE TITLE
How to save and load scenes

### ISSUE THREAD

**Issue by peterchen2001** [BayatGames/node-savegamepro-mysql#2]
Hi, is it possible to save and load scenes created by unity APIs or Save Game Pro?
Here is my scenarios:

I want to create an application using unity with below features:
1,user creates some scenes with a couple of gameobjects(and each gameobject has its components) and save them into database.
2, another user loads these scenes from database stored by step 1 and display the scenes with no data loss.

**Comment by hasanbayatme** [comment]
Hi.
It is possible, but not in the way you guess. (It is an advanced topic)
You need to create Data models and structures for different cases, also you need to have a database of the GameObjects as a ScriptableObject or such.
Then, you can save the data models and instantiate the scene using these data.
For more information, check out below links:

- [Data Model](https://en.wikipedia.org/wiki/Data_model)
- [Data Modeling](https://en.wikipedia.org/wiki/Data_modeling)
- [Data Structure](https://en.wikipedia.org/wiki/Data_structure)

For example, you can have a data model called SceneEntry or whatever, that holds the information required to instantiate this entry.
Each entry can have an identifier which identifies the prefab of the entry in the database and so on.
Thanks.
