### ISSUE TITLE
can you also give unity client scripts

### ISSUE THREAD

**Issue by shubhamguptak** [BayatGames/node-savegamepro-mysql#4]
Hi Can you please also share unity client scripts

**Comment by hasanbayatme** [comment]
Hello.
The client script is already included **SaveGameWeb.cs** file inside **BayatGames/SaveGamePro/Scripts/Networking** folder.

[Learn more about Cloud Saving and Loading](http://docs.bayat.io/savegamepro/manual/guides/cloud-save-load.html)

**Comment by shubhamguptak** [comment]
ok thanks

**Comment by shubhamguptak** [comment]
your github project only includes readme files

**Comment by hasanbayatme** [comment]
The index.js and app.js files should be used for setting up the database.

**Comment by hasanbayatme** [comment]
Also, please follow the [Installation](https://github.com/BayatGames/node-savegamepro-mysql#installation) instructions provided to set up the database.

**Comment by shubhamguptak** [comment]
Hi,
is savegamepro opensource?
Also what i want for my project i want to make a backend with frontend that
can store assetbundles, some images and text. The app can access those
assetbundles with the images and text. Can you please tell me whether
savegamepro supports this functionality so that i can buy it for my
project. I am new to assetbundles and dont have much experience in it. If
you have a backend & frontend  on nodejs and angularjs please let me know.

**Comment by hasanbayatme** [comment]
No, Save Game Pro is a paid asset on the Unity Asset Store, although the integrations are open source.

This integration only provides the backend for handling Save Game Pro requests, unfortunately, no front-end included, and it has no functionality for AssetBundles, so you might have to implement it by yourself or find a third-party component for that.

By the way, these integrations are open source, so you can modify them to your own desire and add the functionally you would and share it with others as well through here.

Maybe the below links would help you out on this manner:

- [AssetBundles](https://docs.unity3d.com/Manual/AssetBundlesIntro.html)
- [Unity Addressable Asset System](https://docs.unity3d.com/Packages/com.unity.addressables@latest)
